[test]
coverage = true # Always enable coverage
# Uncomment to set a minimum coverage threshold
# coverageThreshold = 0.8

[install.scopes]
"@edgefirst-dev" = { url = "https://npm.pkg.github.com", token = "$GITHUB_TOKEN" }
